name: nodejs
description: 'Node.js application'
displayName: Node.js Runtime
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/node-js.svg
versions:
  - version: 2.1.1
  - version: 2.2.0
  - version: 2.2.1
    default: true # should have one and only one default version
