name: go
description: 'Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.'
displayName: Go Runtime
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/golang.svg
versions:
  - version: 1.0.2
  # 1.1.0: debug command via dlv
  - version: 1.1.0
  # 1.2.0: debug command via dlv & go 1.19
  - version: 1.2.0
  # 1.2.1: use https protocol for endpoint
  - version: 1.2.1
    default: true # should have one and only one default version
  # 1.3.0: debug command via dlv & go 1.20
  - version: 1.3.0
  # 1.3.1: use https protocol for endpoint
  - version: 1.3.1
  - version: 2.0.0
  # 2.1.0: debug command via dlv
  - version: 2.1.0
  # 2.2.0: debug command via dlv & go 1.19
  - version: 2.2.0
  # 2.3.0: debug command via dlv & go 1.20
  - version: 2.3.0
  # 2.4.0: debug command via dlv & go 1.21
  - version: 2.4.0
