name: java-wildfly
description: 'JakartaEE  application using WildFly'
displayName: WildFly
icon: https://design.jboss.org/wildfly/logo/final/wildfly_logomark.svg
versions:
  - version: 1.1.0
  - version: 2.0.0
    default: true
 
