name: nodejs-vue
description:
  'Vue is a JavaScript framework for building user interfaces.
    It builds on top of standard HTML, CSS and JavaScript, and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be it simple or complex.'
displayName: Vue
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/vue.svg
versions:
  - version: 1.0.2
    default: true # should have one and only one default version
  - version: 1.1.0
  - version: 1.2.0
