---
apiVersion: v1
kind: Template
metadata:
  name: devfile-registry-acceptance
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: devfile-registry-acceptance-${JOB_NAME}
  spec:
    backoffLimit: 5
    template:
      spec:
        serviceAccountName: registry-acceptance-service-account
        restartPolicy: Never
        containers:
          - image: ${IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: github-mirror-acceptance
            env:
              - name: REGISTRY
                value: ${REGISTRY}
              - name: PROBE_TIMEOUT
                value: ${PROBE_TIMEOUT}
            resources:
              requests:
                cpu: 20m
                memory: 10Mi
              limits:
                cpu: 100m
                memory: 200Mi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: registry-acceptance-service-account
parameters:
- name: IMAGE
  value: quay.io/devfile/devfile-registry-integration
- name: IMAGE_TAG
  value: "next"
  required: true
- name: REGISTRY
  value: "https://registry.stage.devfile.io"
  required: true
- name: PROBE_TIMEOUT
  value: "600"
  description: |- 
    The maximum time in seconds the test suite will wait 
    for the target deployment to be in ready state.
- name: JOB_NAME
  generate: expression
  from: "[a-z0-9]{5}"
