apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-deploy
  name: devfile-dotnet-deploy
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: devfile-dotnet-deploy
  type: LoadBalancer
