name: nodejs-nextjs
description:
  'Next.js gives you the best developer experience with all the features you need for production:
  hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more.
  No config needed.'
displayName: Next.js
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/next-js.svg
versions:
  - version: 1.0.3
    default: true # should have one and only one default version
  - version: 1.1.0
  - version: 1.2.0
