name: java-springboot
description: Spring Boot using Java
displayName: Spring Boot
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/spring.svg
versions:
  - version: 1.2.0
    default: true # should have one and only one default version
  - version: 2.0.0
