name: java-springboot
description: Spring Boot using Java
displayName: Spring Boot
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/spring.svg
versions:
  - version: 1.2.0
  # 1.3.0, 1.4.0: with JDK 17
  - version: 1.3.0
  - version: 1.4.0
    default: true # should have one and only one default version
  - version: 2.0.0
  # 2.1.0, 2.2.0: with JDK 17
  - version: 2.1.0
  - version: 2.2.0
