name: java-springboot
description: Spring Boot using Java
displayName: Spring Boot
icon: https://spring.io/images/projects/spring-edf462fec682b9d48cf628eaf9e19521.svg
versions:
  - version: 1.2.0
    default: true # should have one and only one default version
  - version: 2.0.0
