kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{applicationName}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{applicationName}}'
  template:
    metadata:
      labels:
        app: '{{applicationName}}'
    spec:
      containers:
        - name: '{{applicationName}}'
          image: '{{imageName}}:{{imageVersion}}'
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: '{{applicationName}}-svc'
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: '{{applicationName}}'
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: '{{applicationName}}-route'
spec:
  to:
    kind: Service
    name: '{{applicationName}}-svc'
    weight: 100
  port:
    targetPort: http-8081
  wildcardPolicy: None

