name: nodejs-svelte
description:
  'Svelte is a radical new approach to building user interfaces.
    Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app.'
displayName: Svelte
icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/svelte.svg
versions:
  - version: 1.0.3
    default: true # should have one and only one default version
  - version: 1.1.0
  - version: 1.2.0
