#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Check Architectures

on:
  pull_request:
    branches: [ main ]

jobs:
  check_architectures:
    name: Check Stack and Sample Architectures
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install yq command
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: "github"
        github_pat: ${{ secrets.GITHUB_TOKEN }}
        # Installs the latest release of yq
        yq: "latest"
    - name: test action out
      id: mf
      uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          +(stacks)/**/devfile.yaml
          extraDevfileEntries.yaml
    - name: print diff with env
      run: echo GIT_DIFF ${{ env.GIT_DIFF }}
    - name: Save PR number
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/number
    - name: Check stacks and samples ouput
      continue-on-error: true
      run: tests/check_architectures.sh "${{ env.GIT_DIFF }}" yq >> ./pr/output
    - name: dummy
      continue-on-error: true
      run: tests/check_architectures.sh "${{ env.GIT_DIFF }}" yq
    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
