#
#   Copyright 2021-2022 Red Hat, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
name: Validate Devfiles with odo v3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 5 * * *

jobs:

  test_with_minikube:
    name: Test on Minikube
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.7.0
      with:
        minikube version: 'v1.26.1'
        kubernetes version: 'v1.24.3'
        driver: 'docker'
        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - name: Install odo
      run: |
        git clone https://github.com/redhat-developer/odo /tmp/odo
        cd /tmp/odo
        make install
    - name: "Install Ginkgo"
      run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
    - name: Test Devfiles stacks with odo
      run: tests/run-odov3-tests.sh
